-- Invoice / company detail fields for clients
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "rate_in_person" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "rate_phone" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "rate_virtual" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "rate_mileage" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "rate_travel_time" DOUBLE PRECISION NOT NULL DEFAULT 0;
